### ISSUE TITLE
generated abi encoding string is incorrect when contain uint256[M] type

### ISSUE THREAD

**Issue by ouumuzi** [HashEx/abiencoder#11]
- [x] I know how to publish contract and verify it
- [x] I know how to use the tool

My contract constructor arguments has include `uint256[3] feeSettings`，then I copied form remix abi json and exactly fill every parameter. I copied generated abi code string, but I can not verify my contract.

I did it twice and check every step, but the same result. So I to find only this type argument does not show the right type，I created another contract and remove this type，the part of `uint256[3] feeSettings` using hard-coding， Wow，it  is fine.

So I'm be sure contain argument such as `uint256[M]`type  generate wrong abi encoding. 

 I hope you can fix it as soon as possible!

**Comment by masquel** [comment]
Hey @ouumuzi, can you share your ABI and constructor inputs?
