### ISSUE TITLE
Function Selector calculation appears to be incorrect

### ISSUE THREAD

**Issue by drinkcoffee** [HashEx/abiencoder#19]
The calculation of function selector seems to be wrong.
Error(string) for abiencoder returns 5e8a70b4. It should return 08c379a0
Panic(uint256) for abiencoder returns 08754fa9. It should return 4e487b71

**Comment by drinkcoffee** [comment]
In fact, have a look at the example in the documentation: https://docs.soliditylang.org/en/v0.8.17/abi-spec.html?highlight=abi%20encoding 

baz(uint32,bool) should be 0xcdcd77c0

**Comment by masquel** [comment]
Hey, @drinkcoffee 

`Error(string)` is `08c379a0`
![image](https://user-images.githubusercontent.com/6623392/202847760-51cf5fc5-b727-4cd8-950d-d8e927637b30.png)

`Panic(uint256)` is `4e487b71`
![image](https://user-images.githubusercontent.com/6623392/202847804-45328f12-5b85-4cfc-8280-460b3bf0f48c.png)

`baz(uint32,bool)` is `cdcd77c`
![image](https://user-images.githubusercontent.com/6623392/202847857-35f9cc88-ac4a-437e-ae5d-6a5fbcaa7026.png)
