### ISSUE TITLE
Variable is structure type

### ISSUE THREAD

**Issue by W2Ning** [HashEx/abiencoder#2]
Hello there,

This tool helps me a lot,
I wanna know how to encode a function which has a variable of  structure type.

Thank you.

**Comment by masquel** [comment]
Hey, @W2Ning, maybe you can provide an ABI example, so we can test it?

**Comment by masquel** [comment]
Hey, @W2Ning we added support of struct variables. Please, check out instructions following up this link - https://github.com/HashEx/abiencoder/blob/main/README.md#how-to-encode-struct-arguments
