### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Mentors4EDU** [HashEx/abiencoder#7]
Seems to be a glitch in the code, but after inputing parsed JSON file for ABI w/ constructor arguments, no encoding output is generated. Infact, the encoding generator doesn't have any output for you to copy at all. I tried Edge and Firefox, and used Linux and Windows.

**Comment by Determinant** [comment]
I have the same issue...

**Comment by masquel** [comment]
@Mentors4EDU can you provide inputs?
